const estatusPedido = () => {
  return Math.random() < 0.8;
};

const miPedidoDePizza = new Promise((resolve, reject) => {
  setTimeout(() => {
    if (estatusPedido()) {
      resolve("Pedido Exitoso! Su pizzita esta en camino :D");
    } else {
      reject("Ocurrio un error. Por favor intente nuevamente");
    }
  }, 3000);
});

const manejarPedido = (mensajeDeConfirmaci贸n) => {
  console.log(mensajeDeConfirmaci贸n);
};

const rechazarPedido = (mensajeDeRechazo) => {
  console.log(mensajeDeRechazo);
};

miPedidoDePizza.then(manejarPedido, rechazarPedido);

miPedidoDePizza
    .then((mensajeDeConfirmaci贸n) => {console.log(mensajeDeConfirmaci贸n)})
    .catch((mensajeDeRechazo) => {console.log(mensajeDeRechazo)})